<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	  <UserSecretsId>7f215c30-3034-44b4-93ff-92daedeefb4f</UserSecretsId>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.7" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.7" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.7" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.StackExchangeRedis" Version="8.0.7" />
		<PackageReference Include="StackExchange.Redis" Version="2.8.0" />
		<PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="9.0.3" />
		<PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="9.0.3" />
	</ItemGroup>

</Project>