// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gstream.Data;

#nullable disable

namespace gstream.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250721143440_AddRoomManagement")]
    partial class AddRoomManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("gstream.Models.Data.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("gstream.Models.Data.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BroadcasterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BroadcasterId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BroadcasterId = 1,
                            CreatedAt = new DateTime(2025, 7, 21, 13, 34, 39, 520, DateTimeKind.Utc).AddTicks(6959),
                            Name = "Dummy Room 1",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            BroadcasterId = 1,
                            CreatedAt = new DateTime(2025, 7, 21, 12, 34, 39, 520, DateTimeKind.Utc).AddTicks(6967),
                            Name = "Dummy Room 2",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            BroadcasterId = 1,
                            CreatedAt = new DateTime(2025, 7, 21, 11, 34, 39, 520, DateTimeKind.Utc).AddTicks(6969),
                            Name = "Dummy Room 3",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            BroadcasterId = 1,
                            CreatedAt = new DateTime(2025, 7, 21, 10, 34, 39, 520, DateTimeKind.Utc).AddTicks(6970),
                            Name = "Dummy Room 4",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            BroadcasterId = 1,
                            CreatedAt = new DateTime(2025, 7, 21, 9, 34, 39, 520, DateTimeKind.Utc).AddTicks(6972),
                            Name = "Dummy Room 5",
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            BroadcasterId = 1,
                            CreatedAt = new DateTime(2025, 7, 21, 8, 34, 39, 520, DateTimeKind.Utc).AddTicks(6979),
                            EndedAt = new DateTime(2025, 7, 21, 11, 34, 39, 520, DateTimeKind.Utc).AddTicks(6974),
                            Name = "Dummy Room 6",
                            Status = 3
                        },
                        new
                        {
                            Id = 7,
                            BroadcasterId = 1,
                            CreatedAt = new DateTime(2025, 7, 21, 7, 34, 39, 520, DateTimeKind.Utc).AddTicks(6980),
                            EndedAt = new DateTime(2025, 7, 21, 11, 4, 39, 520, DateTimeKind.Utc).AddTicks(6979),
                            Name = "Dummy Room 7",
                            Status = 3
                        },
                        new
                        {
                            Id = 8,
                            BroadcasterId = 1,
                            CreatedAt = new DateTime(2025, 7, 21, 6, 34, 39, 520, DateTimeKind.Utc).AddTicks(6982),
                            EndedAt = new DateTime(2025, 7, 21, 10, 34, 39, 520, DateTimeKind.Utc).AddTicks(6981),
                            Name = "Dummy Room 8",
                            Status = 3
                        },
                        new
                        {
                            Id = 9,
                            BroadcasterId = 1,
                            CreatedAt = new DateTime(2025, 7, 21, 5, 34, 39, 520, DateTimeKind.Utc).AddTicks(6984),
                            EndedAt = new DateTime(2025, 7, 21, 10, 4, 39, 520, DateTimeKind.Utc).AddTicks(6982),
                            Name = "Dummy Room 9",
                            Status = 3
                        },
                        new
                        {
                            Id = 10,
                            BroadcasterId = 1,
                            CreatedAt = new DateTime(2025, 7, 21, 4, 34, 39, 520, DateTimeKind.Utc).AddTicks(6987),
                            EndedAt = new DateTime(2025, 7, 21, 9, 34, 39, 520, DateTimeKind.Utc).AddTicks(6985),
                            Name = "Dummy Room 10",
                            Status = 3
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 7, 21, 3, 34, 39, 520, DateTimeKind.Utc).AddTicks(6989),
                            Name = "Dummy Room 11",
                            Status = 0
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 7, 21, 2, 34, 39, 520, DateTimeKind.Utc).AddTicks(6990),
                            Name = "Dummy Room 12",
                            Status = 0
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 7, 21, 1, 34, 39, 520, DateTimeKind.Utc).AddTicks(6992),
                            Name = "Dummy Room 13",
                            Status = 0
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 7, 21, 0, 34, 39, 520, DateTimeKind.Utc).AddTicks(6993),
                            Name = "Dummy Room 14",
                            Status = 0
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 7, 20, 23, 34, 39, 520, DateTimeKind.Utc).AddTicks(6994),
                            Name = "Dummy Room 15",
                            Status = 0
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 7, 20, 22, 34, 39, 520, DateTimeKind.Utc).AddTicks(6996),
                            Name = "Dummy Room 16",
                            Status = 0
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 7, 20, 21, 34, 39, 520, DateTimeKind.Utc).AddTicks(6997),
                            Name = "Dummy Room 17",
                            Status = 0
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 7, 20, 20, 34, 39, 520, DateTimeKind.Utc).AddTicks(7000),
                            Name = "Dummy Room 18",
                            Status = 0
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 7, 20, 19, 34, 39, 520, DateTimeKind.Utc).AddTicks(7001),
                            Name = "Dummy Room 19",
                            Status = 0
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 7, 20, 18, 34, 39, 520, DateTimeKind.Utc).AddTicks(7002),
                            Name = "Dummy Room 20",
                            Status = 0
                        });
                });

            modelBuilder.Entity("gstream.Models.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserApiKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserApiKey")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "password",
                            UserApiKey = "testUserApiKey",
                            Username = "testuser"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = "anotherpassword",
                            UserApiKey = "anotherUserApiKey123",
                            Username = "anotheruser"
                        });
                });

            modelBuilder.Entity("gstream.Models.Data.ChatMessage", b =>
                {
                    b.HasOne("gstream.Models.Data.Room", "Room")
                        .WithMany("ChatMessages")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gstream.Models.Data.User", "User")
                        .WithMany("ChatMessages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("gstream.Models.Data.Room", b =>
                {
                    b.HasOne("gstream.Models.Data.User", "Broadcaster")
                        .WithMany("Rooms")
                        .HasForeignKey("BroadcasterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Broadcaster");
                });

            modelBuilder.Entity("gstream.Models.Data.Room", b =>
                {
                    b.Navigation("ChatMessages");
                });

            modelBuilder.Entity("gstream.Models.Data.User", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
