// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gstream.Data;

#nullable disable

namespace gstream.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250721170235_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("gstream.Models.Data.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("gstream.Models.Data.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BroadcasterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BroadcasterId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BroadcasterId = 1,
                            CreatedAt = new DateTime(2025, 7, 21, 16, 2, 34, 562, DateTimeKind.Utc).AddTicks(2394),
                            Name = "Room 1",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            BroadcasterId = 1,
                            CreatedAt = new DateTime(2025, 7, 21, 15, 2, 34, 562, DateTimeKind.Utc).AddTicks(2402),
                            Name = "Room 2",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            BroadcasterId = 1,
                            CreatedAt = new DateTime(2025, 7, 21, 14, 2, 34, 562, DateTimeKind.Utc).AddTicks(2404),
                            Name = "Room 3",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            BroadcasterId = 1,
                            CreatedAt = new DateTime(2025, 7, 21, 13, 2, 34, 562, DateTimeKind.Utc).AddTicks(2405),
                            Name = "Room 4",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            BroadcasterId = 1,
                            CreatedAt = new DateTime(2025, 7, 21, 12, 2, 34, 562, DateTimeKind.Utc).AddTicks(2406),
                            Name = "Room 5",
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            BroadcasterId = 1,
                            CreatedAt = new DateTime(2025, 7, 21, 11, 2, 34, 562, DateTimeKind.Utc).AddTicks(2424),
                            EndedAt = new DateTime(2025, 7, 21, 14, 2, 34, 562, DateTimeKind.Utc).AddTicks(2419),
                            Name = "Room 6",
                            Status = 3
                        },
                        new
                        {
                            Id = 7,
                            BroadcasterId = 1,
                            CreatedAt = new DateTime(2025, 7, 21, 10, 2, 34, 562, DateTimeKind.Utc).AddTicks(2425),
                            EndedAt = new DateTime(2025, 7, 21, 13, 32, 34, 562, DateTimeKind.Utc).AddTicks(2424),
                            Name = "Room 7",
                            Status = 3
                        },
                        new
                        {
                            Id = 8,
                            BroadcasterId = 1,
                            CreatedAt = new DateTime(2025, 7, 21, 9, 2, 34, 562, DateTimeKind.Utc).AddTicks(2427),
                            EndedAt = new DateTime(2025, 7, 21, 13, 2, 34, 562, DateTimeKind.Utc).AddTicks(2426),
                            Name = "Room 8",
                            Status = 3
                        },
                        new
                        {
                            Id = 9,
                            BroadcasterId = 1,
                            CreatedAt = new DateTime(2025, 7, 21, 8, 2, 34, 562, DateTimeKind.Utc).AddTicks(2429),
                            EndedAt = new DateTime(2025, 7, 21, 12, 32, 34, 562, DateTimeKind.Utc).AddTicks(2427),
                            Name = "Room 9",
                            Status = 3
                        },
                        new
                        {
                            Id = 10,
                            BroadcasterId = 1,
                            CreatedAt = new DateTime(2025, 7, 21, 7, 2, 34, 562, DateTimeKind.Utc).AddTicks(2434),
                            EndedAt = new DateTime(2025, 7, 21, 12, 2, 34, 562, DateTimeKind.Utc).AddTicks(2430),
                            Name = "Room 10",
                            Status = 3
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 7, 21, 6, 2, 34, 562, DateTimeKind.Utc).AddTicks(2435),
                            Name = "Room 11",
                            Status = 0
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 7, 21, 5, 2, 34, 562, DateTimeKind.Utc).AddTicks(2437),
                            Name = "Room 12",
                            Status = 0
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 7, 21, 4, 2, 34, 562, DateTimeKind.Utc).AddTicks(2438),
                            Name = "Room 13",
                            Status = 0
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 7, 21, 3, 2, 34, 562, DateTimeKind.Utc).AddTicks(2439),
                            Name = "Room 14",
                            Status = 0
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 7, 21, 2, 2, 34, 562, DateTimeKind.Utc).AddTicks(2440),
                            Name = "Room 15",
                            Status = 0
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 7, 21, 1, 2, 34, 562, DateTimeKind.Utc).AddTicks(2442),
                            Name = "Room 16",
                            Status = 0
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 7, 21, 0, 2, 34, 562, DateTimeKind.Utc).AddTicks(2443),
                            Name = "Room 17",
                            Status = 0
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 7, 20, 23, 2, 34, 562, DateTimeKind.Utc).AddTicks(2445),
                            Name = "Room 18",
                            Status = 0
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 7, 20, 22, 2, 34, 562, DateTimeKind.Utc).AddTicks(2446),
                            Name = "Room 19",
                            Status = 0
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 7, 20, 21, 2, 34, 562, DateTimeKind.Utc).AddTicks(2447),
                            Name = "Room 20",
                            Status = 0
                        });
                });

            modelBuilder.Entity("gstream.Models.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserApiKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserApiKey")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "AQAAAAIAAYagAAAAEJ2glyJVslV2nenWZpfZlc63iwhoGeKosm5cW2sQ83bH84BZsWwbcTfCivW+/9YaoQ==",
                            UserApiKey = "testUserApiKey",
                            Username = "testuser"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = "AQAAAAIAAYagAAAAEOPVRl8UOVWCNwTX3VI+Wa5LqMQmn1PpmqF+JgczCXrfaZWkomlPxgOwroM1n3v+RA==",
                            UserApiKey = "anotherUserApiKey123",
                            Username = "anotheruser"
                        });
                });

            modelBuilder.Entity("gstream.Models.Data.ChatMessage", b =>
                {
                    b.HasOne("gstream.Models.Data.Room", "Room")
                        .WithMany("ChatMessages")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gstream.Models.Data.User", "User")
                        .WithMany("ChatMessages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("gstream.Models.Data.Room", b =>
                {
                    b.HasOne("gstream.Models.Data.User", "Broadcaster")
                        .WithMany("Rooms")
                        .HasForeignKey("BroadcasterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Broadcaster");
                });

            modelBuilder.Entity("gstream.Models.Data.Room", b =>
                {
                    b.Navigation("ChatMessages");
                });

            modelBuilder.Entity("gstream.Models.Data.User", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
