// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gstream.Data;

#nullable disable

namespace gstream.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250722081328_AddUserRolesAndBlocking")]
    partial class AddUserRolesAndBlocking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("gstream.Models.Data.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("gstream.Models.Data.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BroadcasterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BroadcasterId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 7, 22, 7, 13, 27, 639, DateTimeKind.Utc).AddTicks(5774),
                            Name = "Public Room 1",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 7, 22, 6, 13, 27, 639, DateTimeKind.Utc).AddTicks(5784),
                            Name = "Public Room 2",
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 7, 22, 5, 13, 27, 639, DateTimeKind.Utc).AddTicks(5786),
                            Name = "Public Room 3",
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 7, 22, 4, 13, 27, 639, DateTimeKind.Utc).AddTicks(5787),
                            Name = "Public Room 4",
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 7, 22, 3, 13, 27, 639, DateTimeKind.Utc).AddTicks(5789),
                            Name = "Public Room 5",
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 7, 22, 2, 13, 27, 639, DateTimeKind.Utc).AddTicks(5802),
                            Name = "Public Room 6",
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 7, 22, 1, 13, 27, 639, DateTimeKind.Utc).AddTicks(5804),
                            Name = "Public Room 7",
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 7, 22, 0, 13, 27, 639, DateTimeKind.Utc).AddTicks(5805),
                            Name = "Public Room 8",
                            Status = 0
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 7, 21, 23, 13, 27, 639, DateTimeKind.Utc).AddTicks(5807),
                            Name = "Public Room 9",
                            Status = 0
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 7, 21, 22, 13, 27, 639, DateTimeKind.Utc).AddTicks(5812),
                            Name = "Public Room 10",
                            Status = 0
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 7, 21, 21, 13, 27, 639, DateTimeKind.Utc).AddTicks(5835),
                            Name = "Public Room 11",
                            Status = 0
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 7, 21, 20, 13, 27, 639, DateTimeKind.Utc).AddTicks(5913),
                            Name = "Public Room 12",
                            Status = 0
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 7, 21, 19, 13, 27, 639, DateTimeKind.Utc).AddTicks(5915),
                            Name = "Public Room 13",
                            Status = 0
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 7, 21, 18, 13, 27, 639, DateTimeKind.Utc).AddTicks(5926),
                            Name = "Public Room 14",
                            Status = 0
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 7, 21, 17, 13, 27, 639, DateTimeKind.Utc).AddTicks(5937),
                            Name = "Public Room 15",
                            Status = 0
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 7, 21, 16, 13, 27, 639, DateTimeKind.Utc).AddTicks(5939),
                            Name = "Public Room 16",
                            Status = 0
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 7, 21, 15, 13, 27, 639, DateTimeKind.Utc).AddTicks(5941),
                            Name = "Public Room 17",
                            Status = 0
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 7, 21, 14, 13, 27, 639, DateTimeKind.Utc).AddTicks(5944),
                            Name = "Public Room 18",
                            Status = 0
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 7, 21, 13, 13, 27, 639, DateTimeKind.Utc).AddTicks(5946),
                            Name = "Public Room 19",
                            Status = 0
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 7, 21, 12, 13, 27, 639, DateTimeKind.Utc).AddTicks(5947),
                            Name = "Public Room 20",
                            Status = 0
                        });
                });

            modelBuilder.Entity("gstream.Models.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserApiKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserApiKey")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsBlocked = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEMTCP0atLB6yG0ibnU7bCj1KOXq7GE/l2UhrizjTVqfgaDKi74rjmihh2Ubiy7bD2Q==",
                            Role = "Admin",
                            UserApiKey = "adminKey_DO_NOT_USE_IN_PROD",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            IsBlocked = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEE+G+Aft9F6kzD+USHb1vdpfrqRzQY5Kp2ibmwAdK+XBRCkWIlH74Eu0LsB89dAAlw==",
                            Role = "Broadcaster",
                            UserApiKey = "broadcaster1ApiKey",
                            Username = "broadcaster1"
                        },
                        new
                        {
                            Id = 3,
                            IsBlocked = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEN2GJyPJbnB7vdIkKC7p2bX8LVk68yBwoc6Qg0UJNFuX3Cw4gTIUA3YEo+HSmSXs2g==",
                            Role = "Consumer",
                            UserApiKey = "consumer1ApiKey",
                            Username = "consumer1"
                        });
                });

            modelBuilder.Entity("gstream.Models.Data.ChatMessage", b =>
                {
                    b.HasOne("gstream.Models.Data.Room", "Room")
                        .WithMany("ChatMessages")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gstream.Models.Data.User", "User")
                        .WithMany("ChatMessages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("gstream.Models.Data.Room", b =>
                {
                    b.HasOne("gstream.Models.Data.User", "Broadcaster")
                        .WithMany("Rooms")
                        .HasForeignKey("BroadcasterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Broadcaster");
                });

            modelBuilder.Entity("gstream.Models.Data.Room", b =>
                {
                    b.Navigation("ChatMessages");
                });

            modelBuilder.Entity("gstream.Models.Data.User", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
