worker_processes 1;

events {
    worker_connections 1024;
}

http {
    # Define upstream for the gstream app
    upstream gstream_servers {
        server gstream-app-dev:8080; # Must match the container_name
    }

    # Define upstream for the LiveKit server
    upstream livekit_server {
        server gstream-livekit-dev:7880; # Must match the container_name
    }

    server {
        listen 443 ssl;
        server_name 192.168.1.7;

        ssl_certificate /etc/nginx/ssl/cert.pem;
        ssl_certificate_key /etc/nginx/ssl/key.pem;

        location / {
            proxy_pass http://gstream_servers;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /livekit/ {
            proxy_pass http://livekit_server/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }
    }

    server {
        listen 80;
        server_name 192.168.1.7;
        return 301 https://$host$request_uri;
    }
}
